version: '2.4'

services:
    app:
        build:
            context: .
            args:
                UID: ${UID:-1000}
        environment:
            NODE_ENV: development
            DATABASE_USER: thetribe
            DATABASE_PASSWORD: 424242
            DATABASE_HOST: postgres
            DATABASE_NAME: thetribe
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/project
        networks:
            default:
                aliases:
                    - app.local
    postgres:
        image: postgres:10.7
        environment:
            PGUSER: thetribe
            PGPASSWORD: 424242
            POSTGRES_USER: thetribe
            POSTGRES_PASSWORD: 424242
        volumes:
            - db:/var/lib/postgresql/data
    selenium:
        build:
            context: docker/selenium
            args:
                UID: ${UID:-1000}
        environment:
            DISPLAY: ${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
    db:
